// ─── Dealer Configuration ───
// Change these values to customize the site for any golf cart dealer

export const DEALER = {
  name: 'NEXT Level Carts',
  tagline: 'Premium Electric Golf Carts & LSVs — ICON, EPIC, and Denago',
  slogan: 'Take It to the NEXT Level.',
  phone: '',
  email: 'ajones@nxtlevelcarts.com',
  address: '574 W Columbia Ave',
  city: 'Belleville',
  state: 'MI',
  zip: '48111',
  hours: [
    { days: 'Monday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Tuesday – Wednesday', hours: '10:00 AM – 6:00 PM' },
    { days: 'Thursday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Friday', hours: '10:00 AM – 3:00 PM' },
    { days: 'Saturday – Sunday', hours: 'Closed' },
  ],
  social: {
    facebook: 'https://www.facebook.com/profile.php?id=61580448293815',
    instagram: 'https://www.instagram.com/next.level.carts/',
    youtube: '',
  },
  webhookUrl: 'https://n8n.dmsdata.io/webhook/nxt-level-carts-lead',
}

export const COLORS = {
  primary: '#ffcb05',
  primaryDark: '#cc9f04',
  primaryLight: '#ffe135',
  primaryText: '#000',
  accent: '#8B6300',
  dark: '#3a3939',
  charcoal: '#5a5959',
  cream: '#f5f0eb',
  warmGray: '#e8e3de',
}

export const MODELS = [
  {
    name: 'EPIC E40FX',
    brand: 'EPIC',
    type: '4-Passenger Luxury',
    badge: 'PGA Show Winner',
    price: '$14,995',
    image: '/images/epic-e40fx.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '6.3kW AC',
      Battery: '51.2V/105Ah Eco Lithium',
      Range: '40+ miles',
      Display: '10" Multimedia',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10" Multimedia Display',
      'Wireless Charging Pad',
      'Marine-Grade Audio (4 Speakers)',
      'Adjustable Steering Wheel',
      'Push-Button Start & Key Fob',
      'Backup Camera',
      'DOT Compliant & Street Legal',
      '3-Point Restraints',
      '14" Premium Wheels',
    ],
    colors: ['Burgundy', 'Black', 'Midnight Blue', 'Pearl White', 'Cashmere', 'Charcoal'],
  },
  {
    name: 'EPIC E60FX',
    brand: 'EPIC',
    type: '6-Passenger Luxury',
    badge: 'Flagship',
    price: '$16,999',
    image: '/images/epic-e60fx.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '6.3kW AC',
      Battery: '51.2V/105Ah Eco Lithium',
      Range: '40+ miles',
      Display: '10" Multimedia',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10" Multimedia Display',
      'Wireless Charging Pad',
      'Marine-Grade Audio (4 Speakers)',
      'Folding Rear Bench Seats',
      'Push-Button Start & Key Fob',
      'Backup Camera',
      'DOT Compliant & Street Legal',
      'Expandable Storage',
      'Cup Holders Throughout',
    ],
    colors: ['Burgundy', 'Black', 'Midnight Blue', 'Pearl White', 'Cashmere', 'Charcoal'],
  },
  {
    name: 'ICON i40X',
    brand: 'ICON',
    type: '4-Passenger Lifted Electric',
    badge: 'Popular',
    price: '$13,295',
    image: '/images/icon-i40l.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '5kW AC',
      Battery: '51.2V/105Ah Eco Lithium',
      Range: '30–50 miles',
      Display: '10.1" Touchscreen',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10.1" Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'Coil-Over Shock Suspension',
      'Hydraulic Disc Brakes',
      '25% Grade Climb',
      'USB & 12V Ports',
      'LED Headlights',
    ],
    colors: ['White', 'Silver', 'Champagne', 'Black', 'Sangria', 'Forest Green', 'Caribbean Blue'],
  },
  {
    name: 'ICON i60LX',
    brand: 'ICON',
    type: '6-Passenger Lifted Electric',
    badge: 'Family',
    price: '$14,795',
    image: '/images/icon-i60lx.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '5kW AC',
      Battery: '51.2V/105Ah Eco Lithium',
      Range: '30–50 miles',
      Display: '10.1" Touchscreen',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10.1" Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'LED Lighting Package',
      'Extended Seating',
      'Rear Storage',
      'All-Terrain Capable',
      'USB & 12V Ports',
    ],
    colors: ['White', 'Silver', 'Champagne', 'Black', 'Sangria', 'Forest Green', 'Caribbean Blue'],
  },
  {
    name: 'Denago Nomad XL',
    brand: 'Denago',
    type: '4-Passenger Utility',
    badge: 'New',
    price: '$10,995',
    image: '/images/nomad-xl.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '5kW AC',
      Battery: '51.2V/105Ah Lithium',
      Range: '40+ miles',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Rugged Utility Design',
      'All-Terrain Capable',
      'Street Legal',
      'LED Lighting Package',
      'Backup Camera',
      'USB Charging Ports',
    ],
    colors: ['Black', 'White', 'Gray', 'Navy Blue', 'Glacier Blue', 'Aqua', 'Lava Orange', 'Scarlet Red', 'Verdant Green', 'Matte White', 'Matte Black'],
  },
  {
    name: 'Denago Rover XL',
    brand: 'Denago',
    type: '4-Passenger Adventure',
    badge: 'New',
    price: '$11,995',
    image: '/images/rover-xl.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '5kW AC',
      Battery: '51.2V/105Ah Lithium',
      Range: '40+ miles',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Lifted Suspension',
      'All-Terrain Tires',
      'Street Legal',
      'LED Lighting Package',
      'Backup Camera',
      'USB Charging Ports',
    ],
    colors: ['Black', 'White', 'Gray', 'Navy Blue', 'Glacier Blue', 'Aqua', 'Lava Orange', 'Scarlet Red', 'Verdant Green', 'Matte White', 'Matte Black'],
  },
  {
    name: 'Denago Rover XL 6',
    brand: 'Denago',
    type: '6-Passenger Adventure',
    badge: 'New',
    price: '$13,995',
    image: '/images/rover-xl-6.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '5kW AC',
      Battery: '51.2V/105Ah Lithium',
      Range: '40+ miles',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Lifted Suspension',
      '6-Passenger Seating',
      'All-Terrain Tires',
      'Street Legal',
      'LED Lighting Package',
      'Backup Camera',
      'USB Charging Ports',
    ],
    colors: ['Black', 'White', 'Gray', 'Blue', 'Lava Orange', 'Scarlet Red', 'Verdant Green'],
  },
]

export const TESTIMONIALS = [
  {
    name: 'Mike R.',
    location: 'Canton, MI',
    stars: 5,
    text: "Best golf cart buying experience I've ever had. The ICON FX Series is incredible — feels like driving a luxury vehicle. The team at NEXT Level made it easy from start to finish.",
  },
  {
    name: 'Sarah & Tom L.',
    location: 'Ann Arbor, MI',
    stars: 5,
    text: "We bought the i60 for our lake house and couldn't be happier. The kids love it, the neighbors are jealous, and the touchscreen is a game changer. Worth every penny.",
  },
  {
    name: 'Dave K.',
    location: 'Belleville, MI',
    stars: 5,
    text: 'Third cart from NEXT Level. The quality keeps getting better. The lifted ICON handles our property like a champ. Alex and the team always take care of us.',
  },
  {
    name: 'Jennifer P.',
    location: 'Plymouth, MI',
    stars: 5,
    text: "I was nervous about buying a golf cart online but Alex walked me through everything. The ICON Epic exceeded my expectations — the GPS and backup camera are amazing.",
  },
]

export const FINANCING = {
  headline: 'Flexible Financing Available',
  subheadline: "Don't let budget hold you back. We offer competitive financing to get you behind the wheel today.",
  features: [
    'Low monthly payments starting under $200/mo',
    'Terms from 12 to 72 months',
    'Quick approval — most applications approved same day',
  ],
}