// ─── Dealer Configuration ───
// Change these values to customize the site for any golf cart dealer

export const DEALER = {
  name: 'NXT Level Carts',
  tagline: 'Premium Electric Golf Carts',
  slogan: 'Take It to the NXT Level.',
  phone: '',
  email: 'ajones@nxtlevelcarts.com',
  address: '574 W Columbia Ave',
  city: 'Belleville',
  state: 'MI',
  zip: '48111',
  hours: [
    { days: 'Monday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Tuesday – Wednesday', hours: '9:30 AM – 4:30 PM' },
    { days: 'Thursday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Friday', hours: '10:00 AM – 3:00 PM' },
    { days: 'Saturday – Sunday', hours: 'Closed' },
  ],
  social: {
    facebook: '',
    instagram: '',
    youtube: '',
  },
  webhookUrl: 'https://n8n.dmsdata.io/webhook/nxt-level-carts-lead',
}

export const COLORS = {
  primary: '#b03737',
  primaryDark: '#8a2a2a',
  primaryLight: '#d44c4c',
  dark: '#1a1919',
  charcoal: '#2f2e2e',
  cream: '#f5f0eb',
  warmGray: '#e8e3de',
}

export const MODELS = [
  {
    name: 'ICON i40',
    type: '4-Passenger',
    badge: 'Best Seller',
    image: '',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '48V AC',
      Range: 'Up to 40 mi',
      Display: 'Multi-Media Touchscreen',
      Brakes: 'Hydraulic Disc',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'LED Headlights',
      'Push-Button Start',
      'Key Fob Entry',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal', 'Navy', 'Hunter Green'],
  },
  {
    name: 'ICON i60',
    type: '6-Passenger',
    badge: 'Family',
    image: '',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '48V AC',
      Range: 'Up to 40 mi',
      Display: 'Multi-Media Touchscreen',
      Brakes: 'Hydraulic Disc',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'LED Headlights',
      'Extended Roof',
      '3-Point Seatbelts',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal', 'Navy', 'Hunter Green'],
  },
  {
    name: 'ICON FX Series',
    type: 'Award-Winning Performance',
    badge: 'PGA Show Winner',
    image: '',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '48V AC',
      Range: 'Up to 50 mi',
      Display: 'Multi-Media Touchscreen',
      Suspension: 'Independent Front',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Adjustable Steering Wheel',
      'Push-Button Start',
      'Multi-Media Display',
      'Backup Camera',
      '3-Point Restraints',
      'DOT Compliant',
    ],
    colors: ['Alpine White', 'Jet Black', 'Crimson Red', 'Slate Gray', 'Deep Navy'],
  },
  {
    name: 'ICON Epic',
    type: 'Premium Luxury',
    badge: 'Flagship',
    image: '',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '48V AC',
      Range: 'Up to 50 mi',
      Display: 'Touchscreen w/ GPS',
      Suspension: 'Independent Front & Rear',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Touchscreen with GPS',
      'Bluetooth & USB',
      'Premium Blinkers',
      'Storage Compartments',
      'Backup Camera',
      'DOT Street Legal',
    ],
    colors: ['Pearl White', 'Onyx Black', 'Burgundy', 'Metallic Gray', 'British Racing Green'],
  },
  {
    name: 'ICON i20',
    type: '2-Passenger Compact',
    badge: 'Nimble',
    image: '',
    seats: 2,
    category: '2-Seat',
    specs: {
      Seats: '2',
      Motor: '48V AC',
      Range: 'Up to 40 mi',
      Display: 'Digital Dash',
      Brakes: 'Hydraulic Disc',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Compact Design',
      'LED Headlights',
      'Backup Camera',
      'USB Charging',
      'Fold-Down Rear Seat',
      'Easy Parking',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal'],
  },
  {
    name: 'ICON Lifted',
    type: '4-Passenger Off-Road',
    badge: 'Adventure',
    image: '',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '48V AC',
      Range: 'Up to 40 mi',
      Suspension: 'Lifted',
      Tires: 'All-Terrain',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Lifted Suspension',
      'All-Terrain Tires',
      'LED Light Bar',
      'Backup Camera',
      'Heavy-Duty Frame',
      'Off-Road Ready',
    ],
    colors: ['Matte Black', 'Army Green', 'Desert Tan', 'White', 'Red'],
  },
]

export const TESTIMONIALS = [
  {
    name: 'Mike R.',
    location: 'Canton, MI',
    stars: 5,
    text: "Best golf cart buying experience I've ever had. The ICON FX Series is incredible — feels like driving a luxury vehicle. The team at NXT Level made it easy from start to finish.",
  },
  {
    name: 'Sarah & Tom L.',
    location: 'Ann Arbor, MI',
    stars: 5,
    text: "We bought the i60 for our lake house and couldn't be happier. The kids love it, the neighbors are jealous, and the touchscreen is a game changer. Worth every penny.",
  },
  {
    name: 'Dave K.',
    location: 'Belleville, MI',
    stars: 5,
    text: 'Third cart from NXT Level. The quality keeps getting better. The lifted ICON handles our property like a champ. Andrew and the team always take care of us.',
  },
  {
    name: 'Jennifer P.',
    location: 'Plymouth, MI',
    stars: 5,
    text: "I was nervous about buying a golf cart online but Andrew walked me through everything. The ICON Epic exceeded my expectations — the GPS and backup camera are amazing.",
  },
]

export const FINANCING = {
  headline: 'Flexible Financing Available',
  subheadline: "Don't let budget hold you back. We offer competitive financing to get you behind the wheel today.",
  features: [
    'Low monthly payments starting under $200/mo',
    'Terms from 12 to 72 months',
    'Quick approval — most applications approved same day',
    'No prepayment penalties',
    'Trade-ins accepted and valued fairly',
  ],
}
