// ─── Dealer Configuration ───
// Change these values to customize the site for any golf cart dealer

export const DEALER = {
  name: 'NEXT Level Carts',
  tagline: 'Premium Electric Golf Carts',
  slogan: 'Take It to the NEXT Level.',
  phone: '',
  email: 'ajones@nxtlevelcarts.com',
  address: '574 W Columbia Ave',
  city: 'Belleville',
  state: 'MI',
  zip: '48111',
  hours: [
    { days: 'Monday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Tuesday – Wednesday', hours: '9:30 AM – 4:30 PM' },
    { days: 'Thursday', hours: '10:00 AM – 4:00 PM' },
    { days: 'Friday', hours: '10:00 AM – 3:00 PM' },
    { days: 'Saturday – Sunday', hours: 'Closed' },
  ],
  social: {
    facebook: '',
    instagram: 'https://www.instagram.com/next.level.carts/',
    youtube: '',
  },
  webhookUrl: 'https://n8n.dmsdata.io/webhook/nxt-level-carts-lead',
}

export const COLORS = {
  primary: '#b03737',
  primaryDark: '#8a2a2a',
  primaryLight: '#d44c4c',
  dark: '#1a1919',
  charcoal: '#2f2e2e',
  cream: '#f5f0eb',
  warmGray: '#e8e3de',
}

export const MODELS = [
  {
    name: 'EPIC E40FX',
    type: '4-Passenger Luxury',
    badge: 'PGA Show Winner',
    price: '$12,995',
    image: '/images/epic-fx-1.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '6.3kW AC',
      Battery: '51V/105Ah ECO Lithium',
      Range: '40+ miles',
      Display: '10" Multimedia',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10" Multimedia Display',
      'Wireless Charging Pad',
      'Marine-Grade Audio (4 Speakers)',
      'Adjustable Steering Wheel',
      'Push-Button Start & Key Fob',
      'Backup Camera',
      'DOT Compliant & Street Legal',
      '3-Point Restraints',
      '14" Premium Wheels',
    ],
    colors: ['Alpine White', 'Jet Black', 'Crimson Red', 'Slate Gray', 'Deep Navy', 'Hunter Green'],
  },
  {
    name: 'EPIC E60FX',
    type: '6-Passenger Luxury',
    badge: 'Flagship',
    price: '$14,999',
    image: '/images/epic-fx-2.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '6.3kW AC',
      Battery: '51V/105Ah ECO Lithium',
      Range: '40+ miles',
      Display: '10" Multimedia',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10" Multimedia Display',
      'Wireless Charging Pad',
      'Marine-Grade Audio (4 Speakers)',
      'Folding Rear Bench Seats',
      'Push-Button Start & Key Fob',
      'Backup Camera',
      'DOT Compliant & Street Legal',
      'Expandable Storage',
      'Cup Holders Throughout',
    ],
    colors: ['Alpine White', 'Jet Black', 'Crimson Red', 'Slate Gray', 'Deep Navy', 'Hunter Green'],
  },
  {
    name: 'ICON i40L',
    type: '4-Passenger Lifted Electric',
    badge: 'Popular',
    price: '',
    image: '/images/icon-i60lx-white.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '48V 4kW AC',
      Battery: 'Lithium or Lead Acid',
      Range: '30–50 miles',
      Display: '10.1" Touchscreen',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10.1" Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'Coil-Over Shock Suspension',
      'Hydraulic Disc Brakes',
      '25% Grade Climb',
      'USB & 12V Ports',
      'LED Headlights',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal', 'Navy', 'Hunter Green'],
  },
  {
    name: 'ICON i60L',
    type: '6-Passenger Lifted Electric',
    badge: 'Family',
    price: '$15,999',
    image: '/images/epic-fx-3.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '48V 4kW AC',
      Battery: 'Lithium or Lead Acid',
      Range: '30–50 miles',
      Display: '10.1" Touchscreen',
      Speed: 'Up to 25 mph',
    },
    features: [
      '10.1" Touchscreen Display',
      'Bluetooth Audio',
      'Backup Camera',
      'LED Lighting Package',
      'Extended Seating',
      'Rear Storage',
      'All-Terrain Capable',
      'USB & 12V Ports',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal', 'Navy', 'Hunter Green'],
  },
  {
    name: 'EPIC E40L',
    type: '4-Passenger Lifted',
    badge: 'All-Terrain',
    price: '',
    image: '/images/epic-fx-3.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Motor: '6.3kW AC',
      Battery: '51V/105Ah ECO Lithium',
      Range: '40+ miles',
      Suspension: 'Lifted',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Lifted Suspension',
      'All-Terrain Tires',
      'Multimedia Display',
      'Backup Camera',
      'Push-Button Start',
      'Street Legal Certified',
      'DOT Compliant',
      '3-Point Restraints',
    ],
    colors: ['Alpine White', 'Jet Black', 'Crimson Red', 'Slate Gray', 'Deep Navy'],
  },
  {
    name: 'EPIC E60L',
    type: '6-Passenger Lifted',
    badge: 'Adventure',
    price: '$14,235',
    image: '/images/icon-x-1.jpg',
    seats: 6,
    category: '6-Seat',
    specs: {
      Seats: '6',
      Motor: '6.3kW AC',
      Battery: '51V/105Ah ECO Lithium',
      Range: '40+ miles',
      Suspension: 'Lifted',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Lifted Suspension',
      '6-Passenger Seating',
      'All-Terrain Tires',
      'Multimedia Display',
      'Backup Camera',
      'Street Legal Certified',
      'Expandable Storage',
      'LED Lighting Package',
    ],
    colors: ['Alpine White', 'Jet Black', 'Crimson Red', 'Slate Gray', 'Deep Navy'],
  },
  {
    name: 'ICON i20',
    type: '2-Passenger Compact',
    badge: 'Entry',
    price: '',
    image: '/images/icon-x-2.jpg',
    seats: 2,
    category: '2-Seat',
    specs: {
      Seats: '2',
      Motor: '48V AC',
      Battery: 'Multiple Options',
      Range: '30–40 miles',
      Brakes: 'Hydraulic Disc',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Compact Design',
      'LED Headlights',
      'USB Charging',
      'Digital Display',
      'Street Legal Capable',
      'Easy Parking & Storage',
    ],
    colors: ['White', 'Black', 'Red', 'Charcoal'],
  },
  {
    name: 'ICON G40L',
    type: '4-Passenger Gas Lifted',
    badge: 'Gas Powered',
    price: '$12,150',
    image: '/images/icon-i60lx-white.jpg',
    seats: 4,
    category: '4-Seat',
    specs: {
      Seats: '4',
      Engine: '401cc EFI (13.5HP)',
      Fuel: 'Gasoline',
      Brakes: '4-Wheel Disc',
      Display: 'Digital',
      Speed: 'Up to 25 mph',
    },
    features: [
      'Gas-Powered (No Charging Needed)',
      '401cc EFI OHV Engine',
      'Full LED Light Package',
      'Marine-Grade Vinyl Seating',
      'Retractable Seatbelts',
      'Dual Electronic Parking Brake',
      'USB & 12V Ports',
      'Windshield Included',
    ],
    colors: ['White', 'Black', 'Charcoal', 'Hunter Green', 'Navy'],
  },
]

export const TESTIMONIALS = [
  {
    name: 'Mike R.',
    location: 'Canton, MI',
    stars: 5,
    text: "Best golf cart buying experience I've ever had. The ICON FX Series is incredible — feels like driving a luxury vehicle. The team at NEXT Level made it easy from start to finish.",
  },
  {
    name: 'Sarah & Tom L.',
    location: 'Ann Arbor, MI',
    stars: 5,
    text: "We bought the i60 for our lake house and couldn't be happier. The kids love it, the neighbors are jealous, and the touchscreen is a game changer. Worth every penny.",
  },
  {
    name: 'Dave K.',
    location: 'Belleville, MI',
    stars: 5,
    text: 'Third cart from NEXT Level. The quality keeps getting better. The lifted ICON handles our property like a champ. Andrew and the team always take care of us.',
  },
  {
    name: 'Jennifer P.',
    location: 'Plymouth, MI',
    stars: 5,
    text: "I was nervous about buying a golf cart online but Andrew walked me through everything. The ICON Epic exceeded my expectations — the GPS and backup camera are amazing.",
  },
]

export const FINANCING = {
  headline: 'Flexible Financing Available',
  subheadline: "Don't let budget hold you back. We offer competitive financing to get you behind the wheel today.",
  features: [
    'Low monthly payments starting under $200/mo',
    'Terms from 12 to 72 months',
    'Quick approval — most applications approved same day',
    'No prepayment penalties',
    'Trade-ins accepted and valued fairly',
  ],
}
